[build-system]
requires = ["hatchling", "gitpython"]
build-backend = "hatchling.build"

[project]
name='Xnode-Admin'
description='Agent service for Xnode'
urls.source='https://github.com/Openmesh-Network/xnode-admin'
dependencies = ["gitpython"]